title: MD Anayet Hossain
logo: /Assets/IMG_1133-modified.png
description: Hello! I am Anayet, a graphic designer with extensive experience working on diverse projects for various events and companies, where I craft compelling visuals that drive engagement and communicate effectively. In addition to my professional work, I am a co-founder of the Kodom Foundation, a non-profit organization dedicated to uplift the life of the people undertreated by the society; one step at a time. I am passionate about inspiring teams with a visionary approach, encouraging innovative thinking, and embracing creative solutions.
show_downloads: false
theme: jekyll-theme-modernist
